name: Hydra Sync Protocol 🐍 (Native)

on:
  push:
    branches: [ main ]

jobs:
  distribute_traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      # ---------------------------------------------------------
      # 👇 STEP 1: PREPARE CONTENT (Remove Workflow File)
      # ---------------------------------------------------------
      - name: Prepare Content (Remove Workflows)
        run: |
          git config --global user.email "bot@otakunexa.com"
          git config --global user.name "OtakuBot"
          # Delete the automation script from the package we are sending
          git rm -rf .github
          git commit -m "Sync to mirrors (excluding workflow)"

      # =========================================================
      # 7️⃣ MIRROR 7: CyberDrift00
      # =========================================================
      - name: Sync to CyberDrift00
        run: |
          git config --global --unset http.https://github.com/.extraheader || true
          git remote add mirror7 https://CyberDrift00:${{ secrets.PAT_MIRROR_1 }}@github.com/CyberDrift00/anime-index.git
          git push mirror7 main --force
          git remote remove mirror7


     

   

      # =========================================================
      # 5️⃣ MIRROR 5: OtaKuNexa
      # =========================================================
      - name: Sync to OtaKuNexa
        run: |
          git config --global --unset http.https://github.com/.extraheader || true
          git remote add mirror5 https://OtaKuNexa:${{ secrets.PAT_MIRROR_5 }}@github.com/OtaKuNexa/anime-index.git
          git push mirror5 main --force
          git remote remove mirror5


      # =========================================================
      # 7️⃣ MIRROR 7: AhirHero1
      # =========================================================
      - name: Sync to AhirHero
        run: |
          git config --global --unset http.https://github.com/.extraheader || true
          git remote add mirror7 https://otakuhero99-lang:${{ secrets.AHIRHERO }}@github.com/otakuhero99-lang/anime-index.git
          git push mirror7 main --force
          git remote remove mirror7


  

